// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Angara.Html")>]
[<assembly: AssemblyProductAttribute("Angara")>]
[<assembly: AssemblyDescriptionAttribute("The modelling environment")>]
[<assembly: AssemblyVersionAttribute("0.3.2")>]
[<assembly: AssemblyFileVersionAttribute("0.3.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Angara.Html"
    let [<Literal>] AssemblyProduct = "Angara"
    let [<Literal>] AssemblyDescription = "The modelling environment"
    let [<Literal>] AssemblyVersion = "0.3.2"
    let [<Literal>] AssemblyFileVersion = "0.3.2"
